from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.index, name='dashboard-index'),
    path('employee/', views.employee, name='dashboard-employee'),
    path('employee1/', views.employee1, name='dashboard-employee1'),
    path('exportexcel/', views.export_products_xls, name='export-excel'),
    path('exportcsv/', views.export_products_csv, name='export-csv'),
    path('employee/detail/<int:pk>/', views.employee_detail, name='dashboard-employee-detail'),
    path('product/', views.product, name='dashboard-product'),
    path('product/view/<int:pk>/', views.productview, name='dashboard-product-view'),
    path('product1/', views.product1, name='dashboard-product1'),
    path('product2/', views.product2, name='dashboard-product2'),
    path('product_filter', views.product_filter, name='dashboard-product-filter'),
    path('product_filter1', views.product_filter1, name='dashboard-product-filter1'),
    path('product_filter2', views.product_filter2, name='dashboard-product-filter2'),
    path('product/delete/<int:pk>/', views.product_delete, name='dashboard-product-delete'),
    path('product/update/<int:pk>/', views.product_update, name='dashboard-product-update'),
    path('job_order/', views.order, name='dashboard-order'),
    path('job_order_view/<int:pk>/', views.order_view, name='dashboard-order-view'),
    path('job_order_delete/<int:pk>/', views.order_approve, name='dashboard-order-approval'),
    path('about/', views.about, name='dashboard-about'),
    path('disposal/', views.disposal, name='dashboard-disposal'),
    path('employee_list/', views.employee_list, name='dashboard-employee-list'),
    path('employee_list/delete/<int:pk>/', views.employee_delete, name='dashboard-employee-delete'),
    path('procurement/', views.procurement, name='dashboard-procurement'),
    path('assembly/', views.component, name='dashboard-component'),
    path('assembly/view/<int:pk>/', views.component_view, name='dashboard-component-view'),
    path('assembly/update/<int:pk>/', views.assembly_update, name='dashboard-component-update'),
    path('allocation/', views.allocation_view, name='dashboard-allocation'),
    path('malfunctioning_items/', views.malfunction_view, name='dashboard-malfunction'),
    path('no_images/', views.no_image_view, name='dashboard-no-images'),
    path('overall_filter/', views.overall_filter, name='dashboard-overall-filter'),
    path('employee_filter/', views.emp_filter, name='dashboard-employee-filter'),
    path('allocation_filter/', views.alloc_filter, name='dashboard-allocation-filter'),
    path('component_filter/', views.compo_filter, name='dashboard-component-filter'),
    path('disposals/', views.final_disposal, name='dashboard-final-disposal'),
    path('error/', views.error_404, name='dashboard-error'),
    path('job_order_restrict/', views.order_staff, name='dashboard-order-staff'),
]