# Generated by Django 5.0.4 on 2024-05-06 01:00

import dashboard.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_name', models.CharField(max_length=30)),
                ('disposal_serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('disposal_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Disposal',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_name', models.CharField(max_length=100)),
                ('out_name', models.CharField(max_length=100)),
                ('emp_email', models.EmailField(max_length=30, null=True)),
                ('emp_department', models.CharField(choices=[('Operations', 'Operations'), ('Marketing', 'Marketing'), ('IT', 'IT'), ('Management', 'Management'), ('Administration', 'Administration')], max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po', models.CharField(default=dashboard.models.generate_po_number, editable=False, max_length=100)),
                ('classification', models.CharField(blank=True, max_length=50, null=True)),
                ('atn', models.CharField(editable=False, max_length=50, unique=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_type', models.CharField(blank=True, choices=[('Hard Disk Drive', 'Hard Disk Drive'), ('Solid State Drive', 'Solid State Drive'), ('Graphics Card', 'Graphics Card'), ('Laptop', 'Laptop'), ('RAM', 'RAM'), ('Charger', 'Charger'), ('UPS', 'UPS'), ('Mouse', 'Mouse'), ('Keyboard', 'Keyboard'), ('Motherboard', 'Motherboard'), ('Monitor', 'Monitor'), ('Power Supply', 'Power Supply'), ('Router', 'Router'), ('AVR', 'AVR'), ('Tablet', 'Tablet'), ('System Unit', 'System Unit'), ('Audio Devices', 'Audio Devices'), ('CPU', 'CPU'), ('Others', 'Others')], max_length=20)),
                ('site', models.CharField(blank=True, choices=[('Manila', 'Manila'), ('Cebu', 'Cebu')], max_length=250, null=True)),
                ('department', models.CharField(blank=True, choices=[('Operations', 'Operations'), ('Marketing', 'Marketing'), ('IT', 'IT'), ('Management', 'Management'), ('Administration', 'Administration')], max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('OR_number', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('Not Working', 'Not Working'), ('Working', 'Working')], max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('asset_image', models.ImageField(default='Product_Default.png', upload_to='Products')),
                ('adder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jo', models.CharField(default=dashboard.models.generate_jo_number, editable=False, max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('disposal_remarks', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('person_in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee')),
                ('product', models.ForeignKey(error_messages={'unique': 'Job order has been created for this unit/device already.'}, limit_choices_to={'status': 'Not Working'}, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Job Order',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compo_atn', models.CharField(editable=False, max_length=100, null=True)),
                ('compo_name', models.CharField(editable=False, max_length=100, null=True)),
                ('catn', models.CharField(editable=False, max_length=100, null=True)),
                ('date_installed', models.DateField(blank=True, null=True, verbose_name='Installation Date')),
                ('date_replaced', models.DateField(blank=True, null=True, verbose_name='Replace Date')),
                ('activeness', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20, null=True, verbose_name='Status')),
                ('Others', models.CharField(blank=True, max_length=100, null=True)),
                ('HDD1', models.ForeignKey(blank=True, error_messages={'unique': 'This component is already installed in another device!'}, limit_choices_to={'asset_type__in': ['Hard Disk Drive', 'Solid State Drive']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HDD1', to='dashboard.product', unique=True, verbose_name='HDD #1')),
                ('HDD2', models.ForeignKey(blank=True, error_messages={'unique': 'This component is already installed in another device!'}, limit_choices_to={'asset_type__in': ['Hard Disk Drive', 'Solid State Drive']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HDD2', to='dashboard.product', unique=True, verbose_name='HDD #2')),
                ('HDD3', models.ForeignKey(blank=True, error_messages={'unique': 'This component is already installed in another device!'}, limit_choices_to={'asset_type__in': ['Hard Disk Drive', 'Solid State Drive']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HDD3', to='dashboard.product', unique=True, verbose_name='HDD #3')),
                ('HDD4', models.ForeignKey(blank=True, error_messages={'unique': 'This component is already installed in another device!'}, limit_choices_to={'asset_type__in': ['Hard Disk Drive', 'Solid State Drive']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HDD4', to='dashboard.product', unique=True, verbose_name='HDD #4')),
                ('PSU', models.ForeignKey(blank=True, error_messages={'unique': 'This component is already installed in another device!'}, limit_choices_to={'asset_type': 'Power Supply'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PSU', to='dashboard.product', unique=True, verbose_name='Power Supply')),
                ('RAM1', models.ForeignKey(blank=True, error_messages={'unique': 'This component is already installed in another device!'}, limit_choices_to={'asset_type': 'RAM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RAM1', to='dashboard.product', unique=True, verbose_name='RAM #1')),
                ('RAM2', models.ForeignKey(blank=True, error_messages={'unique': 'This component is already installed in another device!'}, limit_choices_to={'asset_type': 'RAM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RAM2', to='dashboard.product', unique=True, verbose_name='RAM #2')),
                ('RAM3', models.ForeignKey(blank=True, error_messages={'unique': 'This component is already installed in another device!'}, limit_choices_to={'asset_type': 'RAM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RAM3', to='dashboard.product', unique=True, verbose_name='RAM #3')),
                ('RAM4', models.ForeignKey(blank=True, error_messages={'unique': 'This component is already installed in another device!'}, limit_choices_to={'asset_type': 'RAM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RAM4', to='dashboard.product', unique=True, verbose_name='RAM #4')),
                ('gpu', models.ForeignKey(blank=True, error_messages={'unique': 'This component is already installed in another device!'}, limit_choices_to={'asset_type': 'Graphics Card'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='GPU', to='dashboard.product', unique=True, verbose_name='GPU')),
                ('motherboard', models.ForeignKey(blank=True, error_messages={'unique': 'This component is already installed in another device!'}, limit_choices_to={'asset_type': 'Motherboard'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motherboard', to='dashboard.product', unique=True)),
                ('processor', models.ForeignKey(blank=True, error_messages={'unique': 'This component is already installed in another device!'}, limit_choices_to={'asset_type': 'CPU'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processor', to='dashboard.product', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Component',
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Room - 2G', 'Room - 2G'), ('Room - 304', 'Room - 304'), ('Room - 305', 'Room - 305'), ('Admin', 'Admin'), ('IT - Room', 'IT - Room'), ('Clinic', 'Clinic'), ('Conference - Room', 'Conference - Room'), ('Others', 'Others')], max_length=30)),
                ('alloc_date', models.DateTimeField(auto_now_add=True)),
                ('system_allocation', models.ForeignKey(blank=True, error_messages={'unique': 'This device is already allocated somewhere else.'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_alloc', to='dashboard.component', unique=True)),
                ('allocation_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee')),
                ('asset_allocation', models.ForeignKey(blank=True, error_messages={'unique': 'This device is already allocated somewhere else.'}, limit_choices_to={'asset_type__in': ['Hard Disk Drive', 'Solid State Drive', 'Graphics Card', 'Laptop', 'RAM', 'Charger', 'UPS', 'Mouse', 'Keyboard', 'Motherboard', 'Monitor', 'Power Supply', 'Router', 'AVR', 'Tablet', 'Audio Devices', 'CPU', 'Others']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_alloc', to='dashboard.product', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Allocation',
            },
        ),
    ]
